//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.22 at 09:17:43 PM UZT 
//


package com.example.resttemplatedemo.model.gcp.schemes;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uz.fidobiznes.esbclientapi.schemes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uz.fidobiznes.esbclientapi.schemes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetDataByDocRequest }
     * 
     */
    public GetDataByDocRequest createGetDataByDocRequest() {
        return new GetDataByDocRequest();
    }

    /**
     * Create an instance of {@link GetDataByDocResponse }
     * 
     */
    public GetDataByDocResponse createGetDataByDocResponse() {
        return new GetDataByDocResponse();
    }

    /**
     * Create an instance of {@link GetDataByPinppRequest }
     * 
     */
    public GetDataByPinppRequest createGetDataByPinppRequest() {
        return new GetDataByPinppRequest();
    }

    /**
     * Create an instance of {@link GetDataByPinppResponse }
     * 
     */
    public GetDataByPinppResponse createGetDataByPinppResponse() {
        return new GetDataByPinppResponse();
    }

    /**
     * Create an instance of {@link CEPRequest }
     * 
     */
    public CEPRequest createCEPRequest() {
        return new CEPRequest();
    }

    /**
     * Create an instance of {@link CEPResponse }
     * 
     */
    public CEPResponse createCEPResponse() {
        return new CEPResponse();
    }

    /**
     * Create an instance of {@link PersonFEntryListRequest }
     * 
     */
    public PersonFEntryListRequest createPersonFEntryListRequest() {
        return new PersonFEntryListRequest();
    }

    /**
     * Create an instance of {@link PersonFEntryListResponse }
     * 
     */
    public PersonFEntryListResponse createPersonFEntryListResponse() {
        return new PersonFEntryListResponse();
    }

}
