//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.24 at 03:23:01 PM UZT 
//


package com.example.mockapi.model.crif.schemes;


import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the uz.fidobiznes.crifkaxclient.schemes package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MGRequest_QNAME = new QName("urn:cbs-messagegatewaysoap:2015-01-01", "MGRequest");
    private final static QName _MGResponse_QNAME = new QName("urn:cbs-messagegatewaysoap:2015-01-01", "MGResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uz.fidobiznes.crifkaxclient.schemes
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MGRequest }
     */
    public MGRequest createMGRequest() {
        return new MGRequest();
    }

    /**
     * Create an instance of {@link MGResponse }
     */
    public MGResponse createMGResponse() {
        return new MGResponse();
    }

    /**
     * Create an instance of {@link Message }
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link MessageCredentials }
     */
    public MessageCredentials createMessageCredentials() {
        return new MessageCredentials();
    }

    /**
     * Create an instance of {@link MessageProduct }
     */
    public MessageProduct createMessageProduct() {
        return new MessageProduct();
    }

    /**
     * Create an instance of {@link MessageResponse }
     */
    public MessageResponse createMessageResponse() {
        return new MessageResponse();
    }

    /**
     * Create an instance of {@link CredentialsResponse }
     */
    public CredentialsResponse createCredentialsResponse() {
        return new CredentialsResponse();
    }

    /**
     * Create an instance of {@link ProductResponse }
     */
    public ProductResponse createProductResponse() {
        return new ProductResponse();
    }



    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MGRequest }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link MGRequest }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cbs-messagegatewaysoap:2015-01-01", name = "MGRequest")
    public JAXBElement<MGRequest> createMGRequest(MGRequest value) {
        return new JAXBElement<MGRequest>(_MGRequest_QNAME, MGRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MGResponse }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link MGResponse }{@code >}
     */
    @XmlElementDecl(namespace = "urn:cbs-messagegatewaysoap:2015-01-01", name = "MGResponse")
    public JAXBElement<MGResponse> createMGResponse(MGResponse value) {
        return new JAXBElement<MGResponse>(_MGResponse_QNAME, MGResponse.class, null, value);
    }

}
