//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.24 at 03:23:01 PM UZT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:cbs-messagegatewaysoap:2015-01-01", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.mockapi.model.crif.schemes;
