//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.24 at 03:23:01 PM UZT 
//


package com.example.resttemplatedemo.model.crif.schemes;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageIdempotence.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MessageIdempotence"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="unique"/&gt;
 *     &lt;enumeration value="idempotent"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "MessageIdempotence")
@XmlEnum
public enum MessageIdempotence {

    @XmlEnumValue("unique")
    UNIQUE("unique"),
    @XmlEnumValue("idempotent")
    IDEMPOTENT("idempotent");
    private final String value;

    MessageIdempotence(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MessageIdempotence fromValue(String v) {
        for (MessageIdempotence c: MessageIdempotence.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
