//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.24 at 03:23:01 PM UZT 
//


package com.example.resttemplatedemo.model.crif.schemes;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for MGResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MGResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MessageResponse" type="{urn:cbs-messagegatewaysoap:2015-01-01}MessageResponse" minOccurs="0"/&gt;
 *         &lt;element name="ProductResponse" type="{urn:cbs-messagegatewaysoap:2015-01-01}ProductResponse" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MGResponse", propOrder = {
    "messageResponse",
    "productResponse"
})
@XmlRootElement(name = "MGResponse")
public class MGResponse {

    @XmlElement(name = "MessageResponse")
    protected MessageResponse messageResponse;
    @XmlElement(name = "ProductResponse")
    protected List<ProductResponse> productResponse;

    /**
     * Gets the value of the messageResponse property.
     * 
     * @return
     *     possible object is
     *     {@link MessageResponse }
     *     
     */
    public MessageResponse getMessageResponse() {
        return messageResponse;
    }

    /**
     * Sets the value of the messageResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageResponse }
     *     
     */
    public void setMessageResponse(MessageResponse value) {
        this.messageResponse = value;
    }

    /**
     * Gets the value of the productResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductResponse }
     * 
     * 
     */
    public List<ProductResponse> getProductResponse() {
        if (productResponse == null) {
            productResponse = new ArrayList<ProductResponse>();
        }
        return this.productResponse;
    }

}
